// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: command.proto

//声明 包名

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 操作码代码
type OperateCode int32

const (
	// 占位符
	OperateCode_NonCode OperateCode = 0 // 连接操作码1-100
	// 设备相关操作
	OperateCode_TurnLeft  OperateCode = 101
	OperateCode_TurnRight OperateCode = 102
	OperateCode_MoveFront OperateCode = 103
	OperateCode_MoveBack  OperateCode = 104
	OperateCode_MoveStop  OperateCode = 105
)

// Enum value maps for OperateCode.
var (
	OperateCode_name = map[int32]string{
		0:   "NonCode",
		101: "TurnLeft",
		102: "TurnRight",
		103: "MoveFront",
		104: "MoveBack",
		105: "MoveStop",
	}
	OperateCode_value = map[string]int32{
		"NonCode":   0,
		"TurnLeft":  101,
		"TurnRight": 102,
		"MoveFront": 103,
		"MoveBack":  104,
		"MoveStop":  105,
	}
)

func (x OperateCode) Enum() *OperateCode {
	p := new(OperateCode)
	*p = x
	return p
}

func (x OperateCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperateCode) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (OperateCode) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x OperateCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperateCode.Descriptor instead.
func (OperateCode) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

type Command_Type int32

const (
	// 连接操作命令，
	Command_Connection Command_Type = 0
	// 设备操作命令
	Command_Device Command_Type = 1
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0: "Connection",
		1: "Device",
	}
	Command_Type_value = map[string]int32{
		"Connection": 0,
		"Device":     1,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[1].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[1]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0, 0}
}

// 命令
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型，
	Type Command_Type `protobuf:"varint,1,opt,name=type,proto3,enum=tmp.Command_Type" json:"type,omitempty"`
	// 消息内容
	Data *Command_Operation `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_Connection
}

func (x *Command) GetData() *Command_Operation {
	if x != nil {
		return x.Data
	}
	return nil
}

type Command_Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcode    int32  `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	Opvalue   int32  `protobuf:"varint,2,opt,name=opvalue,proto3" json:"opvalue,omitempty"`
	Opmessage string `protobuf:"bytes,3,opt,name=opmessage,proto3" json:"opmessage,omitempty"`
}

func (x *Command_Operation) Reset() {
	*x = Command_Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command_Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command_Operation) ProtoMessage() {}

func (x *Command_Operation) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command_Operation.ProtoReflect.Descriptor instead.
func (*Command_Operation) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Command_Operation) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *Command_Operation) GetOpvalue() int32 {
	if x != nil {
		return x.Opvalue
	}
	return 0
}

func (x *Command_Operation) GetOpmessage() string {
	if x != nil {
		return x.Opmessage
	}
	return ""
}

var File_command_proto protoreflect.FileDescriptor

var file_command_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x74, 0x6d, 0x70, 0x22, 0xdd, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x70, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x5b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x70, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x10, 0x01, 0x2a, 0x62, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x54, 0x75, 0x72, 0x6e, 0x4c, 0x65, 0x66, 0x74, 0x10, 0x65, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x75, 0x72, 0x6e, 0x52, 0x69, 0x67, 0x68, 0x74, 0x10, 0x66, 0x12, 0x0d, 0x0a,
	0x09, 0x4d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x10, 0x67, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x10, 0x68, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x6f,
	0x76, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x69, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData = file_command_proto_rawDesc
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_command_proto_rawDescData)
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_command_proto_goTypes = []interface{}{
	(OperateCode)(0),          // 0: tmp.OperateCode
	(Command_Type)(0),         // 1: tmp.Command.Type
	(*Command)(nil),           // 2: tmp.Command
	(*Command_Operation)(nil), // 3: tmp.Command.Operation
}
var file_command_proto_depIdxs = []int32{
	1, // 0: tmp.Command.type:type_name -> tmp.Command.Type
	3, // 1: tmp.Command.data:type_name -> tmp.Command.Operation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command_Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_command_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_rawDesc = nil
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
